.base: &base
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  roles:
    - app
    - db
  deploy_path: ~/deployer/larasun

#10.0.1.59:
#  <<: *base
#  user: nguyen.van.hieu
#  stage: development
#  roles: app
#  become: deploy
#  deploy_path: ~/deployer/larasun

10.0.1.59:
  <<: *base
  user: deploy
  stage: development
  roles: app
  deploy_path: ~/deployer/larasun
